import { SecretRedactor } from '../security/secrets.js';
import { GeminiContent, GeminiPart, GeminiResponse, GeminiToolCall } from './types.js';

export class GeminiApiError extends Error {
  public status: number;
  constructor(message: string, status: number = 500) {
    super(message);
    this.name = 'GeminiApiError';
    this.status = status;
  }
}

export class GeminiService {
  private apiKey: string;
  private model: string;
  private redactor: SecretRedactor;

  constructor(
    apiKey: string,
    model: string = 'gemini-3.8-flash',
    redactor?: SecretRedactor
  ) {
    this.apiKey = apiKey.trim();
    this.model = model.trim();
    this.redactor = redactor || new SecretRedactor([apiKey]);
    this.redactor.addSecret(this.apiKey);
  }

  /**
   * Calls Gemini models via Google GenAI REST API with retries for transient errors.
   */
  public async generateContent(params: {
    systemInstruction?: string;
    contents: GeminiContent[];
    tools?: Array<{
      name: string;
      description: string;
      parameters: Record<string, unknown>;
    }>;
  }): Promise<GeminiResponse> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(
      this.model
    )}:generateContent?key=${encodeURIComponent(this.apiKey)}`;

    const payload: Record<string, unknown> = {
      contents: params.contents,
      generationConfig: {
        temperature: 0.2,
      },
    };

    if (params.systemInstruction) {
      payload.systemInstruction = {
        parts: [{ text: params.systemInstruction }],
      };
    }

    if (params.tools && params.tools.length > 0) {
      payload.tools = [
        {
          functionDeclarations: params.tools,
        },
      ];
    }

    const maxRetries = 2;
    let lastError: Error | null = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'User-Agent': 'aistudio-build',
          },
          body: JSON.stringify(payload),
        });

        if (!response.ok) {
          const errText = await response.text();
          const redactedErr = this.redactor.redact(errText);
          if ((response.status === 429 || response.status >= 500) && attempt < maxRetries) {
            // Transient rate-limit or backend error, wait briefly and retry
            await new Promise((resolve) => setTimeout(resolve, 1000 * (attempt + 1)));
            continue;
          }
          throw new GeminiApiError(
            `Gemini API returned HTTP ${response.status}: ${redactedErr}`,
            response.status
          );
        }

        const data = (await response.json()) as {
          candidates?: Array<{
            content?: {
              parts?: Array<GeminiPart>;
            };
            finishReason?: string;
          }>;
        };

        const candidate = data.candidates?.[0];
        if (!candidate || !candidate.content?.parts) {
          return {
            text: 'No response generated by model.',
          };
        }

        const toolCalls: GeminiToolCall[] = [];
        const textParts: string[] = [];
        const candidateParts: GeminiPart[] = candidate.content.parts;

        for (const part of candidateParts) {
          if (part.functionCall) {
            const thoughtSig = (part as any).thought_signature ||
                               (part as any).thoughtSignature ||
                               (part.functionCall as any).thought_signature ||
                               (part.functionCall as any).thoughtSignature;
            toolCalls.push({
              name: part.functionCall.name,
              args: part.functionCall.args || {},
              part,
              ...(thoughtSig ? {
                thoughtSignature: (part as any).thoughtSignature || (part.functionCall as any).thoughtSignature || thoughtSig,
                thought_signature: (part as any).thought_signature || (part.functionCall as any).thought_signature || thoughtSig,
              } : {}),
            });
          }
          // Do not expose internal thoughts (thought: true) to Telegram output
          if (part.text && !(part as any).thought) {
            textParts.push(part.text);
          }
        }

        return {
          text: textParts.length > 0 ? textParts.join('\n') : undefined,
          toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
          candidateParts: candidateParts.length > 0 ? candidateParts : undefined,
          finishReason: candidate.finishReason,
        };
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        if (attempt < maxRetries && !(err instanceof GeminiApiError && err.status < 500 && err.status !== 429)) {
          await new Promise((resolve) => setTimeout(resolve, 1000 * (attempt + 1)));
          continue;
        }
        break;
      }
    }

    const errorMsg = lastError ? this.redactor.redact(lastError.message) : 'Unknown Gemini error';
    throw new GeminiApiError(`Gemini service failed: ${errorMsg}`, 500);
  }

  /**
   * Connectivity and auth check for health endpoint.
   */
  public async checkHealth(): Promise<boolean> {
    try {
      const res = await this.generateContent({
        contents: [
          {
            role: 'user',
            parts: [{ text: 'ping' }],
          },
        ],
      });
      return !!res.text;
    } catch (err) {
      console.error('Gemini health check error:', err);
      return false;
    }
  }
}
